### ISSUE TITLE
Loading then saving Colors .orc breaks the game's ability to load transforms

### ISSUE THREAD

**Issue by SKmaric** [Radfordhound/HedgeLib#10]
When an original .orc file is loaded and then saved to a new file, the game fails to load the position and rotation data for any objects exported, putting them all at 0,0,0 with no rotation, as pictured:

![image](https://user-images.githubusercontent.com/25527946/30239256-c388fdfa-959b-11e7-94ce-d75065df17a1.png)

It's possible this may be related to the exporter putting each object's individual transform data immediately after the parameter data, instead of all closer to the end of the file like the original ones. This seems to be fine for creating files from scratch, this issue only seems to occur with loading and saving the official files, regardless of any edits made.

Also worth noting, for the current version of HedgeLib the game would crash once any of the objects came in range, I fixed this by adding `writer.FixPadding(4);` at [line 298 of SOBJ.cs](https://github.com/Radfordhound/HedgeLib/blob/master/HedgeLib/Sets/SOBJ.cs#L298).

**Comment by thesupersonic16** [comment]
Oh you found out how to fix the crash. I will give it a try.

**Comment by thesupersonic16** [comment]
Wow it is at 0, 0, 0

![github001](https://user-images.githubusercontent.com/25761885/30239995-2f714d60-95ab-11e7-9325-a4e4a2044d99.png)

**Comment by thesupersonic16** [comment]
Now its crashing.

**Comment by thesupersonic16** [comment]
I think i fixed it, But Its not done right.

**Comment by thesupersonic16** [comment]
It seems it needs padding when moving the transforms. 

Please test this for me its 12:30AM here.

085f45182b683071163d0cf12f3ead6d0e49e2f1

**Comment by SKmaric** [comment]
Ah yes, that fixed it. Thanks!

**Comment by thesupersonic16** [comment]
cool.

**Comment by thesupersonic16** [comment]
I'll update the set editor.

**Comment by Radfordhound** [comment]
Ah I see what was happening with the transforms. Tbh I'm surprised when I programmed the SOBJ class that I made it write the transform data right after the parameters. Thanks for fixing that!

Have no idea what's going on with the game crashing when there's no padding for string parameters, though. I didn't even know there were any objects with string parameters in colors lol. I had that check there just for LW objects.

**Comment by thesupersonic16** [comment]
The best part about this fix is that i found it by mistake. Spent the last 30 mins on constant freezes, I was adding junk into random areas in the SOBJ until it stopped crashing, then i removed some of the junk until it stared crashing, And by doing that I found out that FixPadding seems to stop it from crashing.
