### ISSUE TITLE
Switch to System.Numerics.Vectors

### ISSUE THREAD

**Issue by Radfordhound** [Radfordhound/HedgeLib#14]
Why use my crappy Vector/Quaternion classes when we could use the official classes made by Microsoft that are hardware-accelerated?

**Comment by slashiee** [comment]
how much of a speed boost would this give, if any?

**Comment by Radfordhound** [comment]
They're SIMD hardware accelerated according to MSDN, so calculations like converting from euler angles to quaternions, normalising vectors, etc. should all be at least 2x faster. Though idk how much of a difference that'll really make when using HedgeEdit for example since I try to avoid heavy calculations in the first place.

If anything you'll likely see quicker loading times
