### ISSUE TITLE
HedgeEdit - Options Menu/Redone Config Data

### ISSUE THREAD

**Issue by Radfordhound** [Radfordhound/HedgeLib#19]
We'll need more user data to be stored later on down the road. For example I'm wanting to have themes and control preferences.

I could use the built-in .NET config stuff but tbh I don't really like it lol. There's some limitations on what you can store and I find it to be messy idk. I think it'd be much better to just store configuration data in %appdata%/HedgeEdit as either a custom binary format or just an xml file tbh

**Comment by IchigoDemandsFurryBoobs** [comment]
binary

binary is always the best :dab:

**Comment by thesupersonic16** [comment]
BINA is the best.

**Comment by slashiee** [comment]
BFRES (Binary caFe RESources)

**Comment by IchigoDemandsFurryBoobs** [comment]
nah fam BINA headers are amazing

**Comment by Radfordhound** [comment]
Done :dab: 0acd8a28edf1889b60d6198f81382e8a7c1abb32 & ffb136f4c15f3636235823ebeec4b1899713b5ad
