### ISSUE TITLE
HedgeLib - LW Archive Support (.pac)

### ISSUE THREAD

**Issue by Radfordhound** [Radfordhound/HedgeLib#3]
Shouldn't be too difficult, but I'll need some spare time on-hand so I can fully understand the .pac format.
We'll need code for:

- [X] Extracting LW archives [70be095c806f558674f4c525a5a8b0a454c19512]
- [X] Wrapping BINA data in header/offset tables [b160bea1734a6a2b9421646a9a8ec6b52097c9ac]
- [X] Backwards-compatibility with BINA files extracted with pacpack [e3e8f9128caa1a9404acca758d5cd0e5d0cbd053]
- [x] Creating new LW archives [5b55c6a12a3448cf6410393064b413127cfce6bd]

**Comment by IchigoDemandsFurryBoobs** [comment]
git gud

be like cory

cory knowns what you need boi ;)
![fzmdfgop_400x400](https://user-images.githubusercontent.com/36781469/44380759-d8ab6a00-a4d2-11e8-9121-eed230c2b1ee.jpg)
![hey_there](https://user-images.githubusercontent.com/36781469/44380763-dcd78780-a4d2-11e8-90dd-49fa5fb5e30c.png)
[lel.zip](https://github.com/Radfordhound/HedgeLib/files/2304852/lel.zip)
