### ISSUE TITLE
HedgeCnvrsEditor - System.ArgumentException: "" or System.Xml.XmlException: "&"

### ISSUE THREAD

**Issue by makc-ar** [Radfordhound/HedgeLib#33]
Hi **Radfordhound**! How about export\import Sonic Forces files https://www44.zippyshare.com/v/izYjPerE/file.html ?

**Comment by Sajidur78** [comment]
https://github.com/Radfordhound/HedgeLib/commit/f97b6df6e2dc49e204d7551956cf3218227fcf69 should fix this

**Comment by Sajidur78** [comment]
Reopen this if the issue is still present

**Comment by Sajidur78** [comment]
https://github.com/Radfordhound/HedgeLib/commit/33a54f452d7124f38f6067941bd2950dc2dfc1ad fixed

**Comment by makc-ar** [comment]
Tnanks a lot!
