### ISSUE TITLE
HedgeLib on MacOS

### ISSUE THREAD

**Issue by Radfordhound** [Radfordhound/HedgeLib#36]
*(This isn't an immediate goal, rather a longer-term thing that's optional but would be nice, hence me not adding it to a project/milestone.)*

As I said in the HedgeLib++ video, I'd like HedgeLib to run on as many platforms as possible. That said, I don't own a Mac, nor does my family members, so I don't really have access to one.

Does anyone have a Mac?

If so, I'd really appreciate it if you'd be willing to help me get this to compile/run for you/other Mac users

**Comment by Radfordhound** [comment]
(Already replied in the stream lol but) thanks for the offer!

**Comment by Sajidur78** [comment]
i can help you out on this one if you want i have a bootable hackintosh

**Comment by Radfordhound** [comment]
Hey, thanks a ton for the offer man! I really appreciate it!

Right now everything's in kind of a messy state (most stuff currently isn't compiling due to some stuff I haven't finished), so I'm not sure exactly where to start. I'm trying to get a beta of HedgeArcPack done before July so I'll have a basic version of it compiling again very soon (in a day or two at most); I feel like that'd be a perfect thing to test out once it's ready.

It should all compile fine once I finish up some new stuff since I've been testing on Windows w/ MSVC and Linux w/ gcc (also clang at one point) to make sure my code is properly cross-platform and had no issues compiling (the stuff that's not in a messy state, anyway). Plus I believe xcode actually uses gcc to compile, so it should work just like it does on Linux.

My main concern is with getting it to play nicely with xcode. From what I've seen I believe you can simply download premake to the folder HedgeLib is in, open up a terminal there, and type ```./premake5 xcode4```, though I'm not sure if the project will generate successfully or if it'll work correctly in xcode since, well, xcode is on version 11 now and this was written for version 4 lol (though it's not quite as old as it sounds; xcode 4 was released in late 2016).

If you could try that out and see if you can successfully compile just HedgeLib (not any of the tools just yet), that'd be wonderful! Though take your time, please don't rush!! In any case, thanks a ton for offering once again man!

**Comment by Sajidur78** [comment]
i tried compiling with gcc and things didn't go well. It cant even find the filesystem header

`==== Building HedgeLib (debug_x86) ====
LWArchive.cpp
In file included from src/Archives/LWArchive.cpp:3:
include/HedgeLib/IO/File.h:13:10: fatal error: 'filesystem' file not found
#include <filesystem>
         ^~~~~~~~~~~~
1 error generated.
make[1]: *** [obj/x86/Debug/LWArchive.o] Error 1
make: *** [HedgeLib] Error 2`

**Comment by Radfordhound** [comment]
Ah, yeah that's a pain. filesystem is part of C++17 but for some reason gcc doesn't support it unless you link with ```stdc++fs```. I told the premake script to do that, though, so not sure why it's not working here? Maybe Xcode just comes with an old version of gcc?

**Comment by Radfordhound** [comment]
Ah, I looked it up and it seems Xcode actually uses Clang? My bad, I just assumed it'd be gcc. Tbh, it's been quite a while since I last compiled HedgeLib with Clang. It's probably broken. I'll look into that

**Comment by Radfordhound** [comment]
Just committed 7bbdc710e6a8b58d1700f34c1eb32e217025e064 which makes clang also link stdc++fs, meaning <filesystem> stuff should work under it. It seems this error is related to the actual header, though, so I doubt this will fix it (though might still be worth a shot).

Are you using Xcode or just compiling via the terminal? If you're doing the latter, would you mind generating a project using ```premake5 xcode4``` and trying to compile under Xcode 11? I'm not sure if the gcc version that comes with Xcode is up-to-date which would mean it likely doesn't have a <filesystem> header. Xcode 11 for sure ships with a version of clang that has <filesystem>, so if it still fails to compile due to not being able to find the header there might be a different issue going on.

**Comment by Sajidur78** [comment]
Will make sure to try when I have time

**Comment by Radfordhound** [comment]
No rush! Thanks a lot man

**Comment by Sajidur78** [comment]
Tried building with the latest xcode on apple store and got the same error :/.  As for xcode11 that's not possible yet without a real mac because you need to be on MacOS Catalina which is at beta right now and not possible on a hackintosh _yet_

**Comment by Radfordhound** [comment]
Ah, dang, my bad, I didn't realize that! Well... this might be kind of a nightmare.
If my research is correct, it should at least still support ```<experimental/filesystem>``` (the version of ```<filesystem>``` from before the C++17 standard was finalized), however.

Would you mind replacing all the ```#include <filesystem>``` lines with ```#include <experimental/filesystem>``` and seeing if it compiles? If so I believe I could just change all the
```cpp
#include <filesystem>
```
lines to
```cpp
#ifdef __cpp_lib_filesystem
#include <filesystem>
#else
#include <experimental/filesystem>
#endif

**Comment by Radfordhound** [comment]
2ed16dc45925e9dedf7e4c888d7ab54ac4956178 removes <filesystem> usage meaning HedgeLib now compiles on macOS! I was finally able to test it out despite still not having a mac of my own and can confirm that it actually does compile now.
