### ISSUE TITLE
Change Vector3 etc. to structs

### ISSUE THREAD

**Issue by blueskythlikesclouds** [Radfordhound/HedgeLib#5]
Dear @Radfordhound 
Those are value types, not reference types you're supposed to move from place to place. All of the applications you see most likely has those types as structs.

**Comment by Radfordhound** [comment]
I'm aware of that - and yes, you're right, they should be. I can change Vector3 no problem! The problem simply comes from the way I've set up the Quaternion/Vector4 classes. :P

Basically the Quaternion class extends from the Vector4 class, as I figured the data they both contain is the same thing (4 floats), it's simply the way the two deal with said data that makes them different. As such the way they're read/written is identical, so why make two entirely different types (along with two different read/write methods for each type) when you can just have one extend from the other?

Problem is, structs are implicitly-sealed in C#, which quite simply means that if I make Vector4 a struct I cannot extend it. I might be able to work around this with some ugly hack, such as maybe making an interface lol that contains 4 float properties (X, Y, Z, W), then turning the Vector4/Quaternion classes into structs and then having both of them extend that interface.

But as previously mentioned, that's an ugly hack, and honestly I just don't feel like that's worth it for something like this, as the Vector4/Quaternion classes are honestly big enough in memory (just the 4 floats alone make them both 16 bytes already) that I don't feel there'd honestly be any substantial improvement in efficiency to make such a change worth it.

That and, now that I think about it, there might be some complications with the way I've written some code up until this point lol. For example, if at any point, for whatever reason, I did something like this:

```csharp
foreach (var transform in transforms)
{
    var pos = transform.Position;
    pos.X = 0; // Whatever lol it's just a fricken example, you get the point.
}
```

Then that code would suddenly break without any compiler errors, as it's now no longer getting a reference to the Vector and modifying it's X variable, but instead duplicating the entire Vector and editing the copy. So I'd have to be very careful with a change like this to make sure it doesn't break anything.

**Comment by blueskythlikesclouds** [comment]
fair enough

**Comment by Radfordhound** [comment]
Changed Vector3 type to struct. 3df3c8714be50aa78f353cea1b267be798e4b996
Have to ensure this causes no unintended behavior.
