### ISSUE TITLE
HedgeLib - Tokyo Olympics 2020 Archive Support (.pac)

### ISSUE THREAD

**Issue by Radfordhound** [Radfordhound/HedgeLib#64]
We'll need to:

- [X] Crack the format lol (Some pieces are cracked already, others aren't yet) [[Spec here](https://gist.github.com/Radfordhound/ec23b24251083f76db442406dce7b9e2)]
- [X] Write code for decompressing Tokyo Olympics archives (HedgeLib will have to depend on [lz4](https://github.com/lz4/lz4) for this)
- [X] Write code for extracting Tokyo Olympics archives
- [x] Write code for creating new Tokyo Olympics archives

This game isn't directly related to Sonic (it's not the Mario & Sonic one, it's the one with the humans lol), but it was developed by Sega and is built off of Forces, therefore it's likely this format is going to be reused in some capacity in the next Sonic game, so we might as well add HedgeLib support now.

**Comment by slashiee** [comment]
TOKYO 2020 OLYMPIC GAMES and Shin Sakura Wars has some pac files that are uncompressed.
