### ISSUE TITLE
why are all the issues by the author fix it if you know it

### ISSUE THREAD

**Issue by IchigoDemandsFurryBoobs** [Radfordhound/HedgeLib#67]
how do i make sonic flyin sonic spinball

my brain is just nulls now
![ded brain](https://user-images.githubusercontent.com/36781469/65367133-0b4df780-dbea-11e9-9672-c009f7c986ad.png)

**Comment by thesupersonic16** [comment]
No offence, But you you post art in every issue you make? lol

**Comment by blueskythlikesclouds** [comment]
>shitposting in github

**Comment by Radfordhound** [comment]
epic gamer moment
