### ISSUE TITLE
HedgeEdit - Logo/Icon

### ISSUE THREAD

**Issue by Radfordhound** [Radfordhound/HedgeLib#68]
HedgeLib has had a logo/icon for a while now thanks to Gotta Play Fast, but HedgeEdit currently still doesn't have one.

Ideally I'd like something that stands out somewhat from the HedgeLib logo to make it clear that this isn't HedgeLib (but rather a tool built using HedgeLib), but ofc it can't be too out there or it won't work.

It also needs to come in slightly different forms such that it works well both as a big logo and as a tiny icon in the windows taskbar, as it'll be used in both.

I'm no artist, but I had this idea of an upside-down wrench that kind of looks like a lowercase 'h' which I kind of like. I slapped together a concept to give an idea of what I'm thinking:

**CONCEPT:**

![image](https://user-images.githubusercontent.com/10536295/66244807-d8b6fb00-e6cf-11e9-9bcb-4f5688a1225b.png)

I figure the icon could just be the 'h' wrench:

![image](https://user-images.githubusercontent.com/10536295/66244912-4fec8f00-e6d0-11e9-8e4b-6a315c2a9da5.png)

Though obviously it'd have to be reworked somewhat since this doesn't even properly fit a square shape (icons are usually, like, 32x32, 48x48, 96x96, 128x128, etc.).

Just to make it clear: **Nothing is final about this!!** That's just a concept I slapped together. There's some things about it I'm not fond of already; for example, the shape of the wrench (which is somewhat off and could definitely be improved) and the colors (I picked blue just because "sonic" and because VS uses it and it manages to look good on both dark and light backgrounds there which I thought was a cool trait; obviously the colors aren't final at all and I'm sure it'd look much better with even some minor color tweaks).

In the event that there's someone reading this who has actual artistic talent (unlike me lol), I'd love to hear your thoughts on the above concept and hear some ideas/see some concepts of your own! Once we've settled on a concept we all like, if anyone's willing to help finalize these concepts, I'd love some help with that as well.

Obviously there's no rush or anything; the new editor is (finally) just *beginning* development so we've got plenty of time. Just thought I should mention this now since this definitely will be needed at some point in the future.

**Comment by thesupersonic16** [comment]
Looks pretty cool imo, I also like how it looks like a `h` for HedgeEdit.

**Comment by Radfordhound** [comment]
Huge thanks to [@GreenMarineDev](https://twitter.com/GreenMarineDev) for creating this awesome logo!! I think it's safe to say this is the final. I love this; it's basically exactly what I was picturing (but couldn't get across) when I made that initial concept above.

![HedgeEdit Logo](https://user-images.githubusercontent.com/10536295/69761220-63decb00-112c-11ea-88b4-94d82ddcde69.png)

The icon could either be the "H" wrench, or the "i" checkpoint; though tbh I prefer the "H" as I think it'll help HedgeEdit stand out somewhat from other Sonic level editors. I'll be closing the issue for now, but feel free to reply with your thoughts on this and/or re-open if you feel it necessary.

![Icon](https://user-images.githubusercontent.com/10536295/69761521-3d6d5f80-112d-11ea-86cb-569b2c9447b5.png)
