### ISSUE TITLE
Resaving a terrain model containing sample chunk header doesn't keep its properties

### ISSUE THREAD

**Issue by blueskythlikesclouds** [Radfordhound/HedgeLib#74]
Original:
![image](https://user-images.githubusercontent.com/19259897/128351266-889d853b-38e1-4cdb-8c42-83545cb6f068.png)

Resaved:
![image](https://user-images.githubusercontent.com/19259897/128351310-a46f7e2e-cb02-4365-8409-2e87b0b78994.png)

[The code in question.](https://github.com/Radfordhound/HedgeLib/blob/HedgeLib%2B%2B/HedgeLib/src/models/hl_hh_model.cpp#L2105)

Is this intentional or a mistake? I'm making an issue since I'm not sure how I should be implementing it.

**Comment by Radfordhound** [comment]
Thanks for pointing this out! Yeah, this was a mistake on my part. It seems terrain models each have a single "root node", and sample chunk nodes can be utilized to apply SCA parameters to that node just like in skeletal models. I wasn't accounting for this in my code, so SCA parameters were skipped on read, thus causing them to be missing when resaving the file.

647a89c864401d78c7f8193a6d54a806fba3e280 should fix this. Please let me know if it doesn't!
