### ISSUE TITLE
How can we add the PACx403L format?

### ISSUE THREAD

**Issue by lazenes** [Radfordhound/HedgeLib#76]
Is there anyone among us who creates a function that can read this structure, a structure used for the new sonic game?
Example File:
[text_caption_en.zip](https://github.com/Radfordhound/HedgeLib/files/10206467/text_caption_en.zip)

**Comment by Radfordhound** [comment]
Hey, HedgeLib (and HedgeArcPack) already supports the PACx format used in Origins and Frontiers! 268e43d702a22ac5ad6dcab2e0bb14ab7da19ec7

If you have any issues with this code, please feel free to re-open this issue or create a new issue.
