### ISSUE TITLE
Add support PAC v405 (Sonic x Shadow Generations)

### ISSUE THREAD

**Issue by SmezMorePrakezz** [Radfordhound/HedgeLib#88]
There's a Rom floating on the internet. I extracted it using the available tool, and now I have to deal with this new version of the pac file.

![image](https://github.com/user-attachments/assets/c5359ae3-f8f9-4872-bcb3-7985a572648a)
https://file.io/d6z5KFtIyYy1 is the least spoiling file, Sonic's character file.

**Comment by Radfordhound** [comment]
Thanks for reporting the new format! I'm already on it, will post any updates here.

Apparently if you hex edit the files to replace the '5' with a '3' (so it becomes PACx 403), it actually extracts correctly with HedgeArcPack already. So, they must not have changed too much. I haven't really looked into it myself yet, though, so I'm not sure that this is always the case - it's just what I've heard.

**Comment by SmezMorePrakezz** [comment]
Thank you, I was able to extract the model and other things, but I still have a problem with the DDS texture that isn't fully extracted—however, the model still able extract and still able to convert to FBX with modelfbx.

![image](https://github.com/user-attachments/assets/3e18c316-71e4-474b-b174-594e67a477bf)

**Comment by Radfordhound** [comment]
Hey, so small update:

PACx v405, from my investigation done so far, seems to be the same as PACx v403, except for two extremely minor changes:

- The PACx signature is missing from split files
- Split files no longer have names included; they're now just null pointers.

I presume the game would still function fine if you included both of this data?

In any case, I'm working on a fast commit to allow you to extract/repack these.

**Comment by Radfordhound** [comment]
Added support for PACx v405 with a535c8d

Please reopen and let me know if you have any issues with it.

**Comment by eltoto2019** [comment]
> Thank you, I was able to extract the model and other things, but I still have a problem with the DDS texture that isn't fully extracted—however, the model still able extract and still able to convert to FBX with modelfbx.
> 
> ![image](https://private-user-images.githubusercontent.com/34295880/378839424-3e18c316-71e4-474b-b174-594e67a477bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MDM0NjksIm5iZiI6MTcyOTkwMzE2OSwicGF0aCI6Ii8zNDI5NTg4MC8zNzg4Mzk0MjQtM2UxOGMzMTYtNzFlNC00NzRiLWIxNzQtNTk0ZTY3YTQ3N2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAwMzkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZTk2N2UxZWZhNjJkODU1NzJmZmZlYmIzZmMxMThiNTM3YmRmZWUwMGEzMWNkYjk2YTk1ZDQxZWZhMDEwMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uJQTXEo1RKZtaMrhDUnmQ-S5AB3UvKj-39mHPtYryX0)

help me to convert .model to blender and i can help you to get all the textures
